[package]
name = "pagino"
version = "1.0.0"
authors = ["Behnam Mohammadi <itten@live.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
